site_name: 视觉工作室 2024
copyright: Copyright &copy; 2024 视觉工作室
theme: 
  name: material
  logo: graph/logo.jpg
# pages:
# - [index.md, Home]
# - [about.md, About]
  favicon: graph/logo.jpg
  features:
    - search.highlight
#    - navigation.instant
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
nav:
  - 视觉首页: index.md
  - 关于我们: team/index.md
  - 管理条例: 
    - 条例目录: rule/index.md
    - 设备管理条例: rule/device/index.md
    - 视觉工作室设备租用细则: rule/rent/index.md
    - 浙江大学竺可桢学院全媒体中心章程: rule/constitution/index.md
    - 浙江大学竺可桢学院学生评价实施细则: rule/detail/index.md
    - 竺可桢学院公共空间使用办法（试行）: rule/method/index.md
  - 出锅实录: 
    - 出锅记录表: pot/index.md
  - 视觉周记: 
    - 周记目录: weekly/index.md
  - 相关资源: 
    - 资源目录: resource/index.md
    - 视觉秘籍: resource/book/index.md
    - 全媒体资源: resource/media/index.md
    - 设备说明书: resource/manual/index.md
    - 直播操控台软件: resource/software/index.md
    - 搭建直播系统教程: resource/live/index.md